# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/study/lab2/lab2.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/study/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/study/lab2/lab2.srcs/sources_1/new/lab2.v
read_xdc C:/Users/Administrator/Desktop/study/lab2/lab2.srcs/constrs_1/new/lab2xdc.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/study/lab2/lab2.srcs/constrs_1/new/lab2xdc.xdc]

synth_design -top lab2 -part xc7a100tcsg324-1
write_checkpoint -noxdef lab2.dcp
catch { report_utilization -file lab2_utilization_synth.rpt -pb lab2_utilization_synth.pb }
