# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/study/数逻实验/lab1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/study/数逻实验/lab1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/study/数逻实验/lab1/project_1/project_1.srcs/sources_1/new/lab1.v
read_xdc C:/Users/Administrator/Desktop/study/数逻实验/lab1/project_1/project_1.srcs/constrs_1/new/xqstr.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/study/数逻实验/lab1/project_1/project_1.srcs/constrs_1/new/xqstr.xdc]

synth_design -top lab1 -part xc7a100tcsg324-1
write_checkpoint -noxdef lab1.dcp
catch { report_utilization -file lab1_utilization_synth.rpt -pb lab1_utilization_synth.pb }
