# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sam/Documents/Vivado2015/7SegmentLED/7SegmentLED.cache/wt [current_project]
set_property parent.project_path C:/Users/Sam/Documents/Vivado2015/7SegmentLED/7SegmentLED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/Sam/Documents/Vivado2015/7SegmentLED/7SegmentLED.srcs/sources_1/new/7Seg.v
read_xdc {{C:/Users/Sam/Documents/Vivado2015/7SegmentLED/7SegmentLED.srcs/constrs_1/imports/01 XUP Nexys4 DDR Board/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Sam/Documents/Vivado2015/7SegmentLED/7SegmentLED.srcs/constrs_1/imports/01 XUP Nexys4 DDR Board/Nexys4DDR_Master.xdc}}]

synth_design -top SevenSegmentDisplay -part xc7a100tcsg324-1
write_checkpoint -noxdef SevenSegmentDisplay.dcp
catch { report_utilization -file SevenSegmentDisplay_utilization_synth.rpt -pb SevenSegmentDisplay_utilization_synth.pb }
