# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/study/shuluolab/lab5/lab5_4/lab5_4.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/study/shuluolab/lab5/lab5_4/lab5_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/study/shuluolab/lab5/lab5_4/lab5_4.srcs/sources_1/new/lab5_4.v
read_xdc C:/Users/Administrator/Desktop/study/shuluolab/lab5/lab5_4/lab5_4.srcs/constrs_1/new/lab5_4.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/study/shuluolab/lab5/lab5_4/lab5_4.srcs/constrs_1/new/lab5_4.xdc]

synth_design -top lab5_4 -part xc7a100tcsg324-1
write_checkpoint -noxdef lab5_4.dcp
catch { report_utilization -file lab5_4_utilization_synth.rpt -pb lab5_4_utilization_synth.pb }
